- name: Create directories
  file:
    path: "{{ certbot_path }}/{{ item }}"
    state: directory
    owner: "{{ account.user }}"
    group: "{{ account.user }}"
  loop:
    - accounts
    - ansible
  become: yes

- name: Template compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{ certbot_path }}/docker-compose.yml"
    mode: "644"

- name: Template accounts configuration
  template:
    src: cloudflare.ini.j2
    dest: "{{ certbot_path }}/accounts/{{ item.key }}.ini"
    mode: "600"
  when: item.value.type == "cloudflare"
  loop: "{{ certbot.accounts | default({}) | dict2items }}"

- name: Copy certbot script
  copy:
    src: certbot
    dest: "{{ certbot_path }}/certbot"
    mode: "755"

- name: Get certificates
  include_tasks: get_cert.yml
  loop: "{{ certbot.certs | default({}) | dict2items }}"

- name: Template renew script
  template:
    src: renew.sh.j2
    dest: "{{ certbot_path }}/renew.sh"
    mode: "755"

- name: Install cron
  package:
    name: cron
    state: present
  become: yes

- name: Configure cron task for certificates renew
  cron:
    name: "renew certificates"
    user: root
    minute: "0"
    hour: "4"
    job: "/bin/bash {{ certbot_path }}/renew.sh > /dev/null 2>&1"
  become: yes
